CREATE DATABASE TUAN4_NHOM2_TCSDL204

USE TUAN4_NHOM2_TCSDL204

CREATE TABLE KHACHHANG(
	MAKHACHHANG CHAR(20) PRIMARY KEY,
	TENCONGTY NVARCHAR(50) NOT NULL,
	TENGIAODICH NVARCHAR(50),
	DIACHI NVARCHAR(100),
	EMAIL VARCHAR(30),
	DIENTHOAI VARCHAR(20),
	FAX CHAR(10)
)

CREATE TABLE NHACUNGCAP(
	MACONGTY CHAR(20) PRIMARY KEY,
	TENCONGTY NVARCHAR(50),
	TENGIAODICH NVARCHAR(50),
	DIACHI  VARCHAR(100),
	DIENTHOAI VARCHAR(20),
	EMAIL VARCHAR(30),
	FAX CHAR(10)
)

CREATE TABLE LOAIHANG(
	MALOAIHANG  CHAR(10) PRIMARY KEY,
	TENLOAIHANG NVARCHAR(50) NOT NULL,
)

CREATE TABLE NHANVIEN(
	MANHANVIEN CHAR(15) PRIMARY KEY,
	HO NVARCHAR(20) NOT NULL,
	TEN NVARCHAR(15) NOT NULL,
	NGAYSINH DATE,
	NGAYLAMVIEC DATE,
	DIACHI NVARCHAR(100),
	DIENTHOAI VARCHAR(20),
	LUONGCOBAN MONEY,
	PHUCAP MONEY
)

CREATE TABLE DONDATHANG (
	SOHOADON CHAR(20) PRIMARY KEY,
	MAKHACHHANG CHAR(20),
	MANHANVIEN CHAR(15),
	NGAYDATHANG DATETIME,
	NGAYGIAOHANG DATETIME,
	NGAYCHUYENHANG DATETIME,
	NOIGIAOHANG NVARCHAR(100)
	CONSTRAINT KHACHHANG_DONDATHANG FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG),
	 --FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG)
	FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN),
	CONSTRAINT DIEUKIEN_NGAYGIAO CHECK (NGAYGIAOHANG>=NGAYDATHANG),
	CONSTRAINT CK_NGAY CHECK (
        NGAYGIAOHANG > NGAYCHUYENHANG AND 
        NGAYCHUYENHANG > NGAYDATHANG
    )
)
-- THÊM VÌ THIẾU LIÊN KẾT
--ALTER TABLE DONDATHANG 
--ADD FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN)

--ALTER TABLE DONDATHANG
--ADD CONSTRAINT KHACHHANG_DONDATHANG
--FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG);

--ALTER TABLE KHACHHANG
--ALTER COLUMN DIENTHOAI VARCHAR(20); -- SỬA VÌ SAI KIỂU DL


CREATE TABLE MATHANG(
	MAHANG CHAR(10) PRIMARY KEY,
	TENHANG NVARCHAR(30) NOT NULL,
	MACONGTY CHAR(20),
	MALOAIHANG CHAR(10),
	SOLUONG INT,
	DONVITINH NVARCHAR(20),
	GIAHANG MONEY,
	FOREIGN KEY (MACONGTY) REFERENCES NHACUNGCAP(MACONGTY),
	FOREIGN KEY (MALOAIHANG) REFERENCES LOAIHANG(MALOAIHANG)
)


CREATE TABLE CHITIETDATHANG(
	SOHOADON CHAR(20),
	MAHANG CHAR(10),
	GIABAN MONEY,
	SOLUONG INT,
	MUCGIAMGIA NUMERIC(2,2), -- LÀ XX,XX%  Á
	PRIMARY KEY (SOHOADON,MAHANG),
	FOREIGN KEY (SOHOADON) REFERENCES DONDATHANG(SOHOADON),
	FOREIGN KEY (MAHANG) REFERENCES MATHANG(MAHANG)
)




