CREATE DATABASE TUAN5_NHOM2_TCSDL204

USE TUAN5_NHOM2_TCSDL204

CREATE TABLE KHACHHANG(
	MAKHACHHANG CHAR(20) PRIMARY KEY,
	TENCONGTY NVARCHAR(50) NOT NULL,
	DIACHI NVARCHAR(100) NOT NULL,
	EMAIL VARCHAR(30) UNIQUE,
	DIENTHOAI VARCHAR(11) UNIQUE,
	FAX CHAR(10) UNIQUE,
)

CREATE TABLE NHACUNGCAP(
	MACONGTY CHAR(20) PRIMARY KEY,
	TENCONGTY NVARCHAR(50),
	TENGIAODICH NVARCHAR(50),
	DIACHI  VARCHAR(100),
	DIENTHOAI VARCHAR(20),
	EMAIL VARCHAR(30),
	FAX CHAR(10)
)

CREATE TABLE LOAIHANG(
	MALOAIHANG  CHAR(20) PRIMARY KEY,
	TENLOAIHANG NVARCHAR(50) NOT NULL,
)

CREATE TABLE NHANVIEN(
	MANHANVIEN CHAR(20) PRIMARY KEY,
	HO NVARCHAR(20) NOT NULL,
	TEN NVARCHAR(15) NOT NULL,
	NGAYSINH DATE,
	NGAYLAMVIEC DATE,
	DIACHI NVARCHAR(100),
	DIENTHOAI VARCHAR(11) UNIQUE,
	LUONGCOBAN DECIMAL(10,2),
	PHUCAP DECIMAL(9,2)
)

CREATE TABLE DONDATHANG (
	SOHOADON CHAR(20) PRIMARY KEY,
	MAKHACHHANG CHAR(20),
	MANHANVIEN CHAR(20),
	NGAYDATHANG DATETIME,
	NGAYGIAOHANG DATETIME,
	NGAYCHUYENHANG DATETIME,
	NOIGIAOHANG NVARCHAR(100)
	CONSTRAINT KHACHHANG_DONDATHANG FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG),
	 --FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG)
	CONSTRAINT NHANVIEN_DONDATHANG FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN),
	CONSTRAINT DIEUKIEN_NGAYGIAO CHECK (NGAYGIAOHANG>=NGAYDATHANG),
	CONSTRAINT DIEUKIENNGAY CHECK (
        NGAYGIAOHANG >= NGAYCHUYENHANG AND 
        NGAYCHUYENHANG >= NGAYDATHANG
    )
)
-- THÊM VÌ THIẾU LIÊN KẾT
--ALTER TABLE DONDATHANG 
--ADD FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN)

--ALTER TABLE DONDATHANG
--ADD CONSTRAINT KHACHHANG_DONDATHANG
--FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG);

--ALTER TABLE KHACHHANG
--ALTER COLUMN DIENTHOAI VARCHAR(20); -- SỬA VÌ SAI KIỂU DL


CREATE TABLE MATHANG(
	MAHANG CHAR(10) PRIMARY KEY,
	TENHANG NVARCHAR(30) NOT NULL,
	MACONGTY CHAR(20),
	MALOAIHANG CHAR(20),
	SOLUONG INT,
	DONVITINH NVARCHAR(20),
	GIAHANG MONEY,
	CONSTRAINT NHACUNGCAP_MATHANG FOREIGN KEY (MACONGTY) REFERENCES NHACUNGCAP(MACONGTY),
	CONSTRAINT LOAIHANG_MATHANG FOREIGN KEY (MALOAIHANG) REFERENCES LOAIHANG(MALOAIHANG),
	CONSTRAINT KT_SOLUONG CHECK (
	SOLUONG>0
	)
)


CREATE TABLE CHITIETDATHANG(
	SOHOADON CHAR(20),
	MAHANG CHAR(10),
	GIABAN MONEY,
	SOLUONG INT,
	MUCGIAMGIA DECIMAL(5,2), -- LÀ XX,XX%  Á
	PRIMARY KEY (SOHOADON,MAHANG),
	FOREIGN KEY (SOHOADON) REFERENCES DONDATHANG(SOHOADON),
	FOREIGN KEY (MAHANG) REFERENCES MATHANG(MAHANG),
	CONSTRAINT KT_SOlUONG CHECK (
	SOLUONG >0
	)
)




